accounts/urls.py
from django.conf.urls import url
from . import views


app_name="accounts"

urlpatterns = [
	url(r'^signin/$', views.LoginView.as_view(), name="login"),
	url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
	url(r'^signup/$', views.RegisterView.as_view(), name='register'),
	url(r'^ref/(?P<username>[\w-]+)/$', views.GetRef.as_view(), name='get-referral'),
	url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
	url(r'^profile/$', views.UserProfileView.as_view(), name='userprofile'),
	url(r'^verify_email/(?P<verification_key>[\w-]+)/$', views.EmailVerificationView.as_view(), name='verify-email'),
	url(r'^request_new_password/$', views.PasswordChangeRequestView.as_view(), name='password-request'),
	url(r'^change_password/$', views.PasswordChangeView.as_view(), name='password-change'),
]

msgbox/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^messages/$', views.MessageList.as_view(), name='message-list'),
	url(r'^messages/(?P<receiver_id>\d+)/$', views.MessageView.as_view(), name='create-newmessage'),
	]

wallions/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webcore.urls')),
    url(r'^messages/', include('msgbox.urls')),
	url(r'^', include('imgpost.urls')),
    url(r'^', include('accounts.urls')),


]


urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_shared/header.html
<header>

<a href = "javascript:void(0)" onclick = "document.getElementById('nav').style.display='block';document.getElementById('popupbg').style.display='block'">
<span class="header-nav-button"><i class="material-icons">menu</i></span>
</a>

<div id="logo">
<svg xmlns="http://www.w3.org/2000/svg" width="83" height="30" viewBox="0 0 500.000000 300.000000" preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#555555" stroke="none">
<path d="M310 2745 c246 -429 1494 -2565 1499 -2565 3 0 83 133 176 295 139
240 172 292 181 279 7 -8 85 -141 174 -294 89 -154 165 -280 168 -280 4 0 84
133 177 295 139 240 172 292 181 279 7 -8 85 -141 174 -294 89 -154 165 -280
168 -280 4 0 332 562 730 1248 845 1458 778 1343 755 1316 -10 -12 -346 -497
-748 -1077 -401 -581 -733 -1057 -736 -1057 -8 0 -231 320 -236 340 -3 11 731
1292 1019 1780 61 102 -60 -68 -562 -795 -303 -440 -557 -806 -564 -812 -9
-10 -41 30 -146 183 -74 107 -134 199 -133 203 1 4 155 273 343 597 188 324
351 605 362 624 46 81 -32 -29 -397 -558 -209 -303 -384 -550 -389 -549 -5 2
-184 255 -398 563 -214 307 -396 568 -404 579 -24 32 20 -45 383 -669 189
-325 342 -595 339 -600 -12 -28 -264 -381 -270 -379 -4 1 -266 375 -582 830
-317 455 -578 830 -581 833 -8 6 -45 71 554 -959 277 -476 502 -867 501 -871
-9 -20 -234 -340 -239 -340 -3 0 -343 485 -754 1078 -412 592 -753 1082 -758
1087 -6 6 0 -8 13 -30z m2325 -1589 c63 -110 114 -202 113 -206 -9 -19 -234
-340 -239 -340 -12 0 -233 326 -234 345 0 26 227 417 236 408 4 -5 60 -98 124
-207z"/>
</g>
</svg>
</div>

<form id="header-search" class="hide-mobile">
<button type="submit"><i class="material-icons">search</i></button>
<input type="text" placeholder="Search" maxlength="40" required="required"/>
</form>

<a href = "javascript:void(0)" onclick = "document.getElementById('popup-filters').style.display='block';document.getElementById('popupbg').style.display='block'">
<div id="header-filter" class="hide-mobile"><i class="material-icons">sort</i></div>
</a>

<div id="header-right">
<a href = "javascript:void(0)" onclick = "document.getElementById('logged-in-user-panel').style.display='block';document.getElementById('popupbg').style.display='block'">
<span class="header-right-count">9</span>
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
</a>
</div>

<div id="header-user-portal" class="hide-mobile">
<a href = "javascript:void(0)" onclick = "document.getElementById('user-portal').style.display='block';document.getElementById('popupbg').style.display='block'">
<i class="material-icons">account_circle</i>
</a>
</div>

</header>

templates/_shared/notifications.html
<!--Logged in notification center -->
<div id="notification-center">
<div id="notification-center-content">

<div id="notification-center-item">
<div id="notification-center-item-user">
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
<p>Username favorited your image</p>
<p>1 hours ago</p>
</div>
<div id="notification-center-item-image"><img src="http://wallions.com/wp-content/uploads/2016/05/7999-300x200.jpg"></div>
</div>

<div id="notification-center-item">
<div id="notification-center-item-user">
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
<p>Username commented on your image</p>
<p>8 hours ago</p>
</div>
<div id="notification-center-item-image"><img src="http://wallions.com/wp-content/uploads/2016/03/6208-300x200.jpg"></div>
</div>

<div id="notification-center-item">
<div id="notification-center-item-user">
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
<p>Username followed you</p>
<p>10 hours ago</p>
</div>
<div id="notification-center-item-image"><img src="follow.png"></div>
</div>

<div id="notification-center-item">
<div id="notification-center-item-user">
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
<p>Username favorited your image</p>
<p>14 hours ago</p>
</div>
<div id="notification-center-item-image"><img src="http://wallions.com/wp-content/uploads/2016/07/8940-300x450.jpeg"></div>
</div>

<div id="notification-center-item">
<div id="notification-center-item-user">
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
<p>Username commented on your image</p>
<p>1 day ago</p>
</div>
<div id="notification-center-item-image"><img src="http://wallions.com/wp-content/uploads/2016/05/8443-300x450.jpeg"></div>
</div>

<div id="notification-center-item">
<div id="notification-center-item-user">
<img src="alert.png">
<p>Your image has been removed</p>
<p>4 week ago</p>
</div>
<div id="notification-center-item-image"><img src="alert.png"></div>
</div>

</div>

<div id="notification-center-buttons">
<p>Clear Notifications</p>

<a href = "javascript:void(0)" onclick = "document.getElementById('notification-center').style.display='none';document.getElementById('logged-in-user-panel').style.display='none';document.getElementById('popupbg').style.display='none'">
<p class="notification-center-buttons-close">Close</p>
</a>
</div>

</div>
<!--End Logged in notification center -->

templates/_shared/search_filter.html
<!-- Filters -->
<div id="popup-filters">
<div id="popup-filters-body">


<div id="sorting-filters" class="sorting-filters-border">
<div id="sorting-filters-left"><p>Sort by</p></div>
<div id="sorting-filters-right" class="sorting-categories">
<select>
  <option value="newest">Newest</option>
  <option value="random">Random</option>
  <option value="most-viewed">Most Viewed</option>
  <option value="most-favorited">Most Favorited</option>
</select>
</div>
</div>


<div id="sorting-filters" class="sorting-filters-border">
<div id="sorting-filters-left"><p>Filter by</p></div>
<div id="sorting-filters-right" class="sorting-categories">
<select>
  <option value="images">Images</option>
  <option value="users">Users</option>
</select>
</div>
</div>


<div id="sorting-filters" class="sorting-filters-border">
<div id="sorting-filters-left"><p>Orientation</p></div>
<div id="sorting-filters-right" class="sorting-categories">
<select>
  <option value="newest">All</option>
  <option value="random">Landscape</option>
  <option value="most-viewed">Portrait</option>
  <option value="most-favorited">Square</option>
</select>
</div>
</div>


<div id="sorting-filters" class="sorting-filters-border">
<div id="sorting-filters-left"><p>Resolution</p></div>
<div id="sorting-filters-right" class="sorting-resolution"><input type="text" maxlength="5"> x <input type="text" maxlength="5"></div>
</div>


<div id="sorting-filters" class="sorting-filters-border">
<div id="sorting-filters-left"><p>Aspect Ratio</p></div>
<div id="sorting-filters-right" class="sorting-ratio"><input type="text" maxlength="2"> : <input type="text" maxlength="2"></div>
</div>


<div id="sorting-filters" class="sorting-filters-border hide-mobile">
<div id="sorting-filters-left"><p>Change Layout</p></div>
<div id="sorting-filters-right" class="sorting-layout">
<i class="material-icons">view_comfy</i>
<i class="material-icons">view_compact</i>
</div>
</div>


<div id="sorting-filters">
<div id="sorting-filters-left"><p>Night Mode</p></div>
<div id="sorting-filters-right" class="sorting-layout">
<a href="#" onclick="setActiveStyleSheet('night'); return false;"><i class="material-icons">check</i></a>
<a href="#" onclick="setActiveStyleSheet('default'); return false;"><i class="material-icons">clear</i></a>
</div>
</div>


</div>

<a href = "javascript:void(0)" onclick = "document.getElementById('popup-filters').style.display='none';document.getElementById('popupbg').style.display='none'">
<div id="sorting-filters-close" class="hide-desktop"><p>Close</p></div>
</a>

</div>
<!-- End Filters -->





<!-- Mobile Search -->
<form id="mobile-search" class="hide-desktop">
<button type="submit"><i class="material-icons">search</i></button>
<input type="text" placeholder="Search" maxlength="40" required="required"/>
</form>
<!-- End Mobile Search -->

templates/_shared/user_menu.html
<!--Logged in header user menu -->
<div id="logged-in-user-panel">

<div id="logged-in-user-panel-header">
<img src="http://wallions.com/wp-content/uploads/2016/08/Logo-square-large-150x150.png">
<p>Username</p>
<p>232 posts</p>
<p>666 followers</p>
<p>852 favorites</p>
</div>

<a href = "javascript:void(0)" onclick = "document.getElementById('notification-center').style.display='block';document.getElementById('popupbg').style.display='block'">
<div id="logged-in-user-panel-menu" class="hide-mobile">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">notifications_none</i><p>Notifications</p></div>
<div id="logged-in-user-panel-menu-item-right"><p>6</p></div>
</div>
</a>

<a href = "javascript:void(0)" onclick = "document.getElementById('notification-center').style.display='block';document.getElementById('logged-in-user-panel').style.display='none'">
<div id="logged-in-user-panel-menu" class="hide-desktop">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">notifications_none</i><p>Notifications</p></div>
<div id="logged-in-user-panel-menu-item-right"><p>6</p></div>
</div>
</a>

<a href="messages.html">
<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">email</i><p>Messages</p></div>
<div id="logged-in-user-panel-menu-item-right"><p>3</p></div>
</div>
</a>

<a href="following.html">
<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">check</i><p>Following</p></div>
<div id="logged-in-user-panel-menu-item-right"><i class="material-icons">keyboard_arrow_right</i></div>
</div>
</a>

<a href="upload.html">
<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">file_upload</i><p>Upload</p></div>
<div id="logged-in-user-panel-menu-item-right"><i class="material-icons">keyboard_arrow_right</i></div>
</div>
</a>

<a href="profile.html">
<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">favorite</i><p>Favorites</p></div>
<div id="logged-in-user-panel-menu-item-right"><i class="material-icons">keyboard_arrow_right</i></div>
</div>
</a>

<a href="profile.html">
<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">account_circle</i><p>View Profile</p></div>
<div id="logged-in-user-panel-menu-item-right"><i class="material-icons">keyboard_arrow_right</i></div>
</div>
</a>

<a href="settings.html">
<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">settings</i><p>Settings</p></div>
<div id="logged-in-user-panel-menu-item-right"><i class="material-icons">keyboard_arrow_right</i></div>
</div>
</a>

<div id="logged-in-user-panel-menu">
<div id="logged-in-user-panel-menu-item"><i class="material-icons">exit_to_app</i><p>Sign Out</p></div>
<div id="logged-in-user-panel-menu-item-right"><i class="material-icons">keyboard_arrow_right</i></div>
</div>

</div>
<!--End Logged in header user menu -->

templates/_shared/user_portal.html
<!-- User Portal -->
<div id="user-portal">

<!--Login-->
<div id="SignIn" class="user-portal-content" style="display: block;">
    <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <i class="material-icons">account_circle</i>
    <input type="email" name="usernameoremail" placeholder="Username or Email">
    <i class="material-icons">lock</i>
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Sign In" >
    </form>
    <a href="#" class="tablinks" onclick="openUserPortal(event, 'ForgotPassword')">Forgot Password?</a>
</div>
<!--/Login-->


<!--Sign Up-->
<div id="SignUp" class="user-portal-content">
    <form method="post" action="{% url 'accounts:register' %}">
    {% csrf_token %}
    <i class="material-icons">person</i>
    <input type="text" name="username" placeholder="Username" required>
    <i class="material-icons">email</i>
    <input type="email" name="email" placeholder="Email" required>
    <i class="material-icons">email</i>
    <input type="email" name="email_again" placeholder="Email Again" required>
    <i class="material-icons">lock</i>
    <input type="password" name="password" placeholder="Password" required>
    <i class="material-icons">lock</i>
    <input type="password" name="password_again" placeholder="Password Again" required>
    <input type="submit" value="Sign up">
    </form>
    <a href="#" class="more">Terms and conditions</a>
</div>
<!--/Sign Up-->


<!--Lost Password-->
<div id="ForgotPassword" class="user-portal-content">
    <form>
        {% csrf_token %}
    <i class="material-icons">error</i>
    <input type="email" name="usernameoremail" placeholder="Username or Email">
    <input type="submit" value="Recover">
    </form>
</div>
<!--/Lost Password-->

<div id="user-portal-tabs">
<a href="#" class="tablinks" onclick="openUserPortal(event, 'SignIn')">Sign In</a>
<a href="#" class="tablinks tablinksright" onclick="openUserPortal(event, 'SignUp')">Sign Up</a>
</div>

</div>

<script>
function openUserPortal(evt, portalTab) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("user-portal-content");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(portalTab).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>
<!-- End User Portal -->